package treenipk.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenipk.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.04 13:39:03 // Generated by ComTest
 *
 */
//@SuppressWarnings({ "all" })
//public class MuistiinpanoTest {
//
//
//  // Generated by ComTest BEGIN
//  /** testParse31 */
//  @Test
//  public void testParse31() {    // Muistiinpano: 31
//    Muistiinpano muistiinpano = new Muistiinpano(); 
//    muistiinpano.parse("   2   | olin Santerin kanssa "); 
//    assertEquals("From: Muistiinpano line: 34", "2|olin Santerin kanssa", muistiinpano.toString()); 
//    muistiinpano.rekisteroi(); 
//    int n = muistiinpano.getNro(); 
//    muistiinpano.parse(""+(n+20)); 
//    muistiinpano.rekisteroi(); 
//    assertEquals("From: Muistiinpano line: 40", n+20+1, muistiinpano.getTunnusNro()); 
//    assertEquals("From: Muistiinpano line: 41", "" + (n+20+1) + "|olin Santerin kanssa", muistiinpano.toString()); 
//  } // Generated by ComTest END
//
//
//  // Generated by ComTest BEGIN
//  /** testToString55 */
//  @Test
//  public void testToString55() {    // Muistiinpano: 55
//    Muistiinpano muistiinpano = new Muistiinpano(); 
//    muistiinpano.parse("   2   |  olin Santerin kanssa "); 
//    assertEquals("From: Muistiinpano line: 58", "2|olin Santerin kanssa", muistiinpano.toString()); 
//  } // Generated by ComTest END
//
//
//  // Generated by ComTest BEGIN
//  /** testRekisteroi114 */
//  @Test
//  public void testRekisteroi114() {    // Muistiinpano: 114
//    Muistiinpano pitsi1 = new Muistiinpano(); 
//    assertEquals("From: Muistiinpano line: 116", 0, pitsi1.getTunnusNro()); 
//    pitsi1.rekisteroi(); 
//    Muistiinpano pitsi2 = new Muistiinpano(); 
//    pitsi2.rekisteroi(); 
//    int n1 = pitsi1.getTunnusNro(); 
//    int n2 = pitsi2.getTunnusNro(); 
//    assertEquals("From: Muistiinpano line: 122", n2-1, n1); 
//  } // Generated by ComTest END
//}