package treenipk.test;
// Generated by ComTest BEGIN
import java.util.*;
import java.io.*;
import static org.junit.Assert.*;
import org.junit.*;
import treenipk.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.04 14:14:06 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TreenipaivakirjaTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa24 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa24() throws SailoException {    // Treenipaivakirja: 24
    Treenipaivakirja treenipaivakirja = new Treenipaivakirja(); 
    Treeni aku1 = new Treeni(), aku2 = new Treeni(); 
    treenipaivakirja.lisaa(aku1); 
    treenipaivakirja.lisaa(aku2); 
    treenipaivakirja.lisaa(aku1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaMuistiinpanot44 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaMuistiinpanot44() throws SailoException {    // Treenipaivakirja: 44
    Treenipaivakirja treenipaivakirja = new Treenipaivakirja(); 
    Treeni aku1 = new Treeni(), aku2 = new Treeni(), aku3 = new Treeni(); 
    aku1.rekisteroi(); aku2.rekisteroi(); aku3.rekisteroi(); 
    int id1 = aku1.getTunnusNro(); 
    int id2 = aku2.getTunnusNro(); 
    Muistiinpano pitsi11 = new Muistiinpano(id1); treenipaivakirja.lisaa(pitsi11); 
    Muistiinpano pitsi12 = new Muistiinpano(id1); treenipaivakirja.lisaa(pitsi12); 
    Muistiinpano pitsi21 = new Muistiinpano(id2); treenipaivakirja.lisaa(pitsi21); 
    Muistiinpano pitsi22 = new Muistiinpano(id2); treenipaivakirja.lisaa(pitsi22); 
    Muistiinpano pitsi23 = new Muistiinpano(id2); treenipaivakirja.lisaa(pitsi23); 
    List<Muistiinpano> loytyneet; 
    loytyneet = treenipaivakirja.annaMuistiinpanot(aku3); 
    assertEquals("From: Treenipaivakirja line: 61", 0, loytyneet.size()); 
    loytyneet = treenipaivakirja.annaMuistiinpanot(aku1); 
    assertEquals("From: Treenipaivakirja line: 63", 2, loytyneet.size()); 
    assertEquals("From: Treenipaivakirja line: 64", true, loytyneet.get(0) == pitsi11); 
    assertEquals("From: Treenipaivakirja line: 65", true, loytyneet.get(1) == pitsi12); 
    loytyneet = treenipaivakirja.annaMuistiinpanot(aku2); 
    assertEquals("From: Treenipaivakirja line: 67", 3, loytyneet.size()); 
    assertEquals("From: Treenipaivakirja line: 68", true, loytyneet.get(0) == pitsi21); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta108 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta120() throws SailoException {    // Rekisteri: 120
    Treenipaivakirja rekisteri = new Treenipaivakirja(); 
    Treeni lumo = new Treeni(); lumo.taytahiihtoTreeniTiedoilla(); lumo.rekisteroi(); 
    Treeni lumo1 = new Treeni(); lumo1.taytahiihtoTreeniTiedoilla(); lumo1.rekisteroi(); 
    Muistiinpano SM1 = new Muistiinpano(); SM1.vastaaMuistiinpano(lumo1.getTunnusNro()); 
    Muistiinpano SM2 = new Muistiinpano(); SM2.vastaaMuistiinpano(lumo.getTunnusNro()); 
    String hakemisto = "testitpk"; 
    File dir = new File(hakemisto); 
    File ftied  = new File(hakemisto+"/testimp.dat"); 
    File fhtied = new File(hakemisto+"/testitreenit.dat"); 
    dir.mkdir(); 
    ftied.delete(); 
    fhtied.delete(); 
    try {
    rekisteri.lueTiedostosta(hakemisto); 
    } catch(SailoException _e_){ _e_.getMessage(); }
    rekisteri.lisaa(lumo); 
    rekisteri.lisaa(lumo1); 
    rekisteri.lisaa(SM1); 
    rekisteri.lisaa(SM2); 
    rekisteri.tallenna(); 
  }

}