package treenipk.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import treenipk.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.04 13:56:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TreenitTest {


  // Generated by ComTest BEGIN
  /** testLisaa38 */
  @Test
  public void testLisaa38() {    // Treenit: 38
    Treenit treenit = new Treenit(); 
    Treeni hiihto1 = new Treeni(), hiihto2 = new Treeni(); 
    assertEquals("From: Treenit line: 41", 0, treenit.getLkm()); 
    treenit.lisaa(hiihto1); assertEquals("From: Treenit line: 42", 1, treenit.getLkm()); 
    treenit.lisaa(hiihto2); assertEquals("From: Treenit line: 43", 2, treenit.getLkm()); 
    treenit.lisaa(hiihto1); assertEquals("From: Treenit line: 44", 3, treenit.getLkm()); 
    assertEquals("From: Treenit line: 45", hiihto1, treenit.anna(0)); 
    assertEquals("From: Treenit line: 46", hiihto2, treenit.anna(1)); 
    assertEquals("From: Treenit line: 47", hiihto1, treenit.anna(2)); 
    assertEquals("From: Treenit line: 48", false, treenit.anna(1) == hiihto1); 
    assertEquals("From: Treenit line: 49", true, treenit.anna(1) == hiihto2); 
    treenit.lisaa(hiihto1); assertEquals("From: Treenit line: 50", 4, treenit.getLkm()); 
    treenit.lisaa(hiihto1); assertEquals("From: Treenit line: 51", 5, treenit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta111 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta111() throws SailoException {    // Treenit: 111
    Treenit treenit = new Treenit(); 
    Treeni hiihto1 = new Treeni(), hiihto2 = new Treeni(); 
    hiihto1.taytahiihtoTreeniTiedoilla(); 
    hiihto2.taytahiihtoTreeniTiedoilla(); 
    String tiedNimi = "testitreenit"; 
    File ftied = new File(tiedNimi+".dat"); 
    ftied.delete(); 
    treenit.lisaa(hiihto1); 
    treenit.lisaa(hiihto2); 
    treenit.tallenna("testitpk"); 
    treenit = new Treenit();  // Poistetaan vanhat luomalla uusi
    treenit.lueTiedostosta("testitpk");  // johon ladataan tiedot tiedostosta.
    treenit.lisaa(hiihto2); 
    treenit.tallenna("testitpk"); 
    assertEquals("From: Treenit line: 133", false, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Treenit line: 135", false, fbak.delete()); 
  } // Generated by ComTest END
}